spring:
  profiles:
    active: ${ACTIVE_PROFILE}
---

spring:
  profile: production
  
  rabbitmq.host: ${RABBITMQ_HOST}
  rabbitmq.port: ${RABBITMQ_PORT}
  rabbitmq.username: ${RABBITMQ_USERNAME}
  rabbitmq.password: ${RABBITMQ_PASSWORD}
  rabbitmq.queue: ${RABBITMQ_QUEUE}
  rabbitmq.exchange: ${RABBITMQ_EXCHANGE}
  
  mail:
    host: smtp.gmail.com
    port: ${MAIL_PORT}
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
 
server:
  port: 8082

---
spring:
  profile: local
  
  rabbitmq.host: localhost
  rabbitmq.port: 5672
  rabbitmq.username: guest
  rabbitmq.password: guest
  rabbitmq.queue: birthday-queue
  rabbitmq.exchange: birthday-exchange
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    
server:
    port: 8082    