<!DOCTYPE html>
<html>
<head>
    <title>Warm Wishes</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            padding: 20px;
        }
        
        h1 {
            color: #e74c3c;
            text-align: center;
        }
        
        .container {
            max-width: 600px;
            margin: 0 auto;
            background-color: #fff;
            padding: 30px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }
        
        .image-container {
            text-align: center;
            margin-bottom: 30px;
        }
        
        img {
            max-width: 500px;
            border-radius: 10%;
        }
        
        p {
            line-height: 1.6;
            margin-bottom: 15px;
        }
        
        .signature {
            font-weight: bold;
            text-align: left;
        }
       .tricolor-text {
            font-size: 24px;
            font-weight: bold;
            text-align: center;
            display: inline-block;
        }

        .saffron {
            color: #FF9933;
        }

        .white {
            color: #dbd7ca;
        }

        .green {
            color: #138808;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="tricolor-text">
        <span class="saffron">Happy</span>
        <span class="white"> Independence</span>
        <span class="green"> Day</span>
    </div>
        <div class="image-container">
            <img src="https://raw.githubusercontent.com/Shashank2707/Well-wisher/deployment/consumer/src/main/resources/templates/assets/Independanceday.jpg" alt="Birthday Image">
        </div>
        <p>Hi ${name},</p>
        
           <p>Wishing you a day filled with the hues of courage, the rhythm of unity, and the symphony of freedom! 🇮🇳 As we embrace Independence Day, let's remember the sacrifices that paved the way for our liberty and celebrate the spirit that binds us together.</p>

           <p>The tricolor soars high, whispering stories of valor and resilience. It's a reminder that we are part of a tapestry woven with diverse threads, each contributing to the vibrant fabric of our nation.</p>

           <p>So, here's to the heroes of yesterday, the spirit of today, and the promise of tomorrow. Let's revel in the joy of being part of this incredible journey. Happy Independence Day!</p>

           <br/>
             <p>Stay spirited,
           </p>     
        <div class="signature">
            <p>With warmest wishes,</p>
            <p>Well Wisher Team</p>
        </div>
    </div>
</body>
</html>

