<!DOCTYPE html>
<html>
<head>
    <title>Birthday Wishes</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            padding: 20px;
        }
        
        h1 {
            color: #e74c3c;
            text-align: center;
        }
        
        .container {
            max-width: 600px;
            margin: 0 auto;
            background-color: #fff;
            padding: 30px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }
        
        .image-container {
            text-align: center;
            margin-bottom: 30px;
        }
        
        img {
            max-width: 500px;
            border-radius: 10%;
        }
        
        p {
            line-height: 1.6;
            margin-bottom: 15px;
        }
        
        .signature {
            font-weight: bold;
            text-align: left;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Happy ${occasion}!,</h1>
        <div class="image-container">
            <img src="https://github.com/Shashank2707/Well-wisher/blob/documentation/docs/Architecture.png?raw=true" alt="Birthday Image">
        </div>
        <p>Dear ${name},</p>
        
        <p>Wishing you a day filled with joy, laughter, and wonderful memories as you celebrate another year of your incredible journey around the sun. May this special day bring you closer to your dreams, surrounded by the love and warmth of your dear ones.</p>
        
        <p>On your day, I want you to know how much you mean to me and how grateful I am to have you in my life. Your presence brightens my days and your contagious enthusiasm inspires me to reach for the stars. Thank you for being an amazing friend/family member/colleague!</p>
        
        <p>May the year ahead be filled with countless blessings, exciting adventures, and opportunities that bring you closer to your passions. May you always find the strength to overcome challenges, the courage to pursue your dreams, and the wisdom to embrace every precious moment.</p>
        
        <p>Once again, happy birthday! May this day mark the beginning of a new chapter filled with happiness, success, and endless possibilities. Enjoy your special day to the fullest and know that you are loved and cherished beyond measure.</p>
        
        <div class="signature">
            <p>With warmest wishes,</p>
            <p>Well Wisher Team</p>
        </div>
    </div>
</body>
</html>