spring:
  profiles:
    active: ${ACTIVE_PROFILE}
---

spring:
  profile: production
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_USERNAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL92Dialect
    
  rabbitmq.host: ${RABBITMQ_HOST}
  rabbitmq.port: ${RABBITMQ_PORT}
  rabbitmq.virtualhost: ${RABBITMQ_VIRTUALHOST}
  rabbitmq.username: ${RABBITMQ_USERNAME}
  rabbitmq.password: ${RABBITMQ_PASSWORD}
  rabbitmq.queue: ${RABBITMQ_QUEUE}
  rabbitmq.exchange: ${RABBITMQ_EXCHANGE}
  rabbitmq.broadcastQueue: ${RABBITMQ_BROADCAST_QUEUE}
  rabbitmq.broadcastExchange: ${RABBITMQ_BROADCAST_EXCHANGE}
 
server:
  port: 8080

---
spring:
  profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/utkarshdb
    username: postgres
    password: postgres
    
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL92Dialect
    show-sql: true
    
  rabbitmq.host: localhost
  rabbitmq.port: 5672
  rabbitmq.virtualhost: virtualhost
  rabbitmq.username: guest
  rabbitmq.password: guest
  rabbitmq.queue: birthday-queue
  rabbitmq.exchange: birthday-exchange
  rabbitmq.broadcastQueue: broadcast-queue
  rabbitmq.broadcastExchange: broadcast-exchange
    
server:
    port: 8080   
    